### ISSUE TITLE
Error after Update to v2

### ISSUE THREAD

**Issue by Shoekrates** [clickpress/contao-clickpress-grid#12]
Hi!
After updating from version 1.5.3 to version v2.0 (Contao 5.3, PHP 8.3) the frontend stops working.
In the log files the following is found:
`
[2024-10-30T09:02:06.724491+01:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Too few arguments to function Contao\CoreBundle\Routing\ScopeMatcher::isBackendRequest(), 0 passed in /www/htdocs/wxxxxx/vendor/clickpress/contao-clickpress-grid/src/Element/GridStart.php on line 45 and exactly 1 expected")." at html.html.twig line 6 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Too few arguments to function Contao\\CoreBundle\\Routing\\ScopeMatcher::isBackendRequest(), 0 passed in /www/htdocs/wxxxxx/vendor/clickpress/contao-clickpress-grid/src/Element/GridStart.php on line 45 and exactly 1 expected\"). at /www/htdocs/wxxxxx/vendor/contao/core-bundle/contao/templates/twig/content_element/html.html.twig:6)\n[previous exception] [object] (ArgumentCountError(code: 0): Too few arguments to function Contao\\CoreBundle\\Routing\\ScopeMatcher::isBackendRequest(), 0 passed in /www/htdocs/wxxxxx/vendor/clickpress/contao-clickpress-grid/src/Element/GridStart.php on line 45 and exactly 1 expected at /www/htdocs/wxxxxx/vendor/contao/core-bundle/src/Routing/ScopeMatcher.php:50)"} {"request_uri":"https://www.domain.de/","request_method":"GET"}
`

Opening an article in the backend where grid elements from the previous version are in, results in an internal server error:
`Too few arguments to function Contao\CoreBundle\Routing\ScopeMatcher::isBackendRequest(), 0 passed in /www/htdocs/wxxxxx/vendor/clickpress/contao-clickpress-grid/src/Element/GridStart.php on line 45 and exactly 1 expected`

Going back to v1.5.3 and everything is OK again.

**Comment by stefansl** [comment]
Hi, thanks for reporting. I tested in 5.4 only 🙈

**Comment by stefansl** [comment]
Fixed in https://github.com/clickpress/contao-clickpress-grid/commit/50346101e6547762f44298e6aad6bc97ecf494f4

**Comment by Shoekrates** [comment]
Thanks for the fast fix! Works so far after updating.
